"""empty message

Revision ID: 942f96ab039f
Revises: dff22d1a5088
Create Date: 2020-04-27 18:27:11.346091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '942f96ab039f'
down_revision = 'dff22d1a5088'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('screen_name', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('followers_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('tweet', sa.Column('embedding', sa.PickleType(), nullable=True))
    op.add_column('tweet', sa.Column('full_text', sa.String(length=512), nullable=True))
    op.add_column('tweet', sa.Column('user_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'tweet', 'user', ['user_id'], ['id'])
    op.drop_column('tweet', 'name')
    op.drop_column('tweet', 'handle')
    op.drop_column('tweet', 'tweet')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tweet', sa.Column('tweet', sa.VARCHAR(length=280), nullable=True))
    op.add_column('tweet', sa.Column('handle', sa.VARCHAR(length=128), nullable=True))
    op.add_column('tweet', sa.Column('name', sa.VARCHAR(length=256), nullable=True))
    op.drop_constraint(None, 'tweet', type_='foreignkey')
    op.drop_column('tweet', 'user_id')
    op.drop_column('tweet', 'full_text')
    op.drop_column('tweet', 'embedding')
    op.drop_table('user')
    # ### end Alembic commands ###
